/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crons from "../crons";
import type * as http from "../http";
import type * as mail from "../mail";
import type * as myHttpActions from "../myHttpActions";
import type * as openAi from "../openAi";
import type * as utils from "../utils";
import type * as yt from "../yt";
import type * as ytAction from "../ytAction";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  http: typeof http;
  mail: typeof mail;
  myHttpActions: typeof myHttpActions;
  openAi: typeof openAi;
  utils: typeof utils;
  yt: typeof yt;
  ytAction: typeof ytAction;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
